### ISSUE TITLE
Teacher/ Classes Functionality Phase 2

### ISSUE THREAD

**Issue by olhachemerynska** [mathgizmo/gizmo#292]

**Comment by odonata95** [comment]
- [x] CI: Default due time should be shown on 'Assignments of classname' page.
- [ ] CI: Make 'today's date' the default start date on 'Assignments of class' page.
- [ ] CI: Update data on TO DO section for example, every minute (because for the reason: I was waiting for assignment to start by having the 'to do' page open on my screen… but it did not open itself, I had to refresh the browser.)
- [ ] CI: The topic should have a few lessons. After finished the one of the lessons the following text should be present on the page: ‘You have unfinished lessons in this topic’.
- [ ] CI: when finish placement test and user placed on the lesson N, mark all lessons to lessons N-1 as DONE if user passed placement test, mark all lessons as DONE. If all topics DONE in unit, unit should be marked as Done with the same logic. Admin> Participant: Add ‘Testout’ field that will show that that lesson is done via placement.
- [ ] CI: Add two radio buttons: ‘Lessons could be completed in their order’ & ‘Lessons could be completed in any order’ to each assignment on Create Assignment/Edit Assignment> Manage Assignments page. This functionality should be applied for all users. Make sure that default assignments still act as before: for regular user they should follow the order, for superuser they could selected in any order.
- [x] Turn off the ‘superuser’ role for new all registered user.
- [ ] CI: If you finish the topic, ‘Go to next topic’ button should be present on the page
- [x] Admin: fix pagination
